/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.paasta.caas.api.clusters.namespaces;

import lombok.Data;

import java.util.List;
import java.util.Map;

/**
 * ResourceQuotaSpec defines the desired hard limits to enforce for Quota.
 */
@Data
public class ResourceQuotaSpec {

  private Map<String, String> hard = null;
//  private V1ScopeSelector scopeSelector = null;
  private List<String> scopes = null;

}

