/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.paasta.caas.api.clusters.namespaces;

import lombok.Data;

import java.util.HashMap;
import java.util.Map;

/**
 * ResourceQuotaStatus defines the enforced hard limits and observed use.
 */
@Data
public class ResourceQuotaStatus {

  private Map<String, String> hard;
  private Map<String, String> used;

  public ResourceQuotaStatus hard(Map<String, String> hard) {
    this.hard = hard;
    return this;
  }

  public ResourceQuotaStatus putHardItem(String key, String hardItem) {
    if (this.hard == null) {
      this.hard = new HashMap<String, String>();
    }
    this.hard.put(key, hardItem);
    return this;
  }


  public Map<String, String> getHard() {
    return hard;
  }

  public void setHard(Map<String, String> hard) {
    this.hard = hard;
  }

  public ResourceQuotaStatus used(Map<String, String> used) {
    this.used = used;
    return this;
  }

  public ResourceQuotaStatus putUsedItem(String key, String usedItem) {
    if (this.used == null) {
      this.used = new HashMap<String, String>();
    }
    this.used.put(key, usedItem);
    return this;
  }

}

