/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.paasta.caas.api.clusters.namespace;

import lombok.Data;
import org.paasta.caas.api.common.model.CommonMetaData;

/**
 * ResourceQuota sets aggregate quota restrictions enforced per namespace
 */
@Data
public class ResourceQuota {

  private String apiVersion;
  private String kind;
  private CommonMetaData metadata;
  private ResourceQuotaSpec spec;
  private ResourceQuotaStatus status;

}

