/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.11.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.paasta.caas.api.clusters.namespace;

import lombok.Data;

import java.util.List;

/**
 * ResourceQuotaList is a list of ResourceQuota items.
 */
@Data
public class ResourceQuotaList {

  private String resultCode;
  private List<ResourceQuota> items;

}

